"""
ui/pages/curation.py — Phase 4: Curation Layer 1 — Candidate Review (SPEC-05 S-05.5).

Streamlit page for Phase 4.  Displays deterministic curation candidates
generated by the five zero-LLM detectors (SPEC-05 S-05.1):

  - Exact node duplicates
  - Exact relationship duplicates
  - Probable duplicates (Jaro-Winkler ≥ 0.90)
  - Canonical / inverse violations
  - Structural anomalies (orphans, degree outliers, missing provenance,
    qualifier gaps)

Workflow:
  1. User clicks "Generate Candidates" → POST /api/curation/candidates/generate.
  2. Page shows count summary per detector type on success.
  3. Full candidate list is loaded from GET /api/curation/candidates/{run_id}
     on every page render (reads from 5-minute cache, fast after generation).
  4. Candidates are displayed in one expander per detector type, sorted by
     severity (critical first), with per-group severity badge counts.

Architecture rules:
  - No business logic — pure API calls and display (CLAUDE.md §4.1, SKILL-B).
  - All session state via StateManager.get() — no direct st.session_state
    access anywhere in this file (CLAUDE.md §8).
  - API calls via httpx synchronous client (Streamlit is single-threaded).
  - Panels degrade gracefully when the API is unreachable (SKILL-D R-D12).

Backend endpoints consumed:
  POST /api/curation/candidates/generate  — run all five detectors
  GET  /api/curation/candidates/{run_id}  — grouped, cached candidate list
"""

import os
from typing import Any

import httpx
import streamlit as st

from api.models.run import Phase
from ui.state import StateManager

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

_API_BASE_URL: str = os.environ.get("API_BASE_URL", "http://localhost:8000")
# Candidate generation reads Neo4j; allow extra time beyond the default.
_REQUEST_TIMEOUT: float = 15.0

# ---------------------------------------------------------------------------
# Display helpers
# ---------------------------------------------------------------------------

_SEVERITY_BADGE: dict[str, str] = {
    "critical": ":red[CRITICAL]",
    "high": ":orange[HIGH]",
    "medium": ":blue[MEDIUM]",
    "low": ":gray[LOW]",
}

_TYPE_LABELS: dict[str, str] = {
    "exact_node_duplicate": "Exact Node Duplicates",
    "exact_rel_duplicate": "Exact Relationship Duplicates",
    "probable_duplicate": "Probable Duplicates",
    "canonical_violation": "Canonical / Inverse Violations",
    "structural_anomaly": "Structural Anomalies",
}

# ---------------------------------------------------------------------------
# API helpers — errors return None / error tuple, never raise
# ---------------------------------------------------------------------------


def _fetch(path: str) -> dict[str, Any] | None:
    """GET {_API_BASE_URL}{path} and return parsed JSON or None on any error."""
    try:
        with httpx.Client(timeout=_REQUEST_TIMEOUT) as c:
            r = c.get(f"{_API_BASE_URL}{path}")
            r.raise_for_status()
            return r.json()  # type: ignore[no-any-return]
    except Exception:
        return None


def _post(
    path: str, payload: dict[str, Any]
) -> tuple[dict[str, Any] | None, str | None]:
    """POST {_API_BASE_URL}{path} with JSON body. Returns (data, error)."""
    try:
        with httpx.Client(timeout=_REQUEST_TIMEOUT) as c:
            r = c.post(f"{_API_BASE_URL}{path}", json=payload)
            return r.json(), None  # type: ignore[no-any-return]
    except Exception as exc:
        return None, str(exc)


# ---------------------------------------------------------------------------
# Panel renderers — pure presentation, no state mutations
# ---------------------------------------------------------------------------


def _render_trigger_section(run_id: str) -> None:
    """Render the candidate generation trigger button and inline count summary.

    The POST endpoint is idempotent within the 5-minute cache TTL: clicking
    the button while a fresh cached result exists returns the cached counts
    immediately without re-querying Neo4j.
    """
    st.subheader("Generate Candidates")
    st.caption(
        "Runs all five deterministic detectors against the current Neo4j graph "
        "for this run.  Zero-LLM — results are fully reproducible.  Cached for "
        "5 minutes; re-click to force a fresh detection pass after the TTL expires."
    )

    if st.button(
        "Generate Candidates",
        type="primary",
        help="Runs exact-dup, probable-dup, canonical-violation, and structural-anomaly detectors.",
    ):
        with st.spinner("Running candidate detection…"):
            data, err = _post(
                "/api/curation/candidates/generate",
                {"run_id": run_id},
            )

        if err or data is None:
            st.error(
                f"Candidate generation failed: {err or 'No response from API.'}"
            )
            return

        if data.get("status") == "error":
            for e in data.get("errors", []):
                code = e.get("code", "")
                if code == "schema_not_locked":
                    st.error(
                        "Domain schema is not locked. Complete Phase 1 "
                        "(Domain Schema) before generating candidates."
                    )
                else:
                    st.error(f"[{code}] {e.get('message')}")
            return

        total: int = data.get("total_count", 0)
        counts: list[dict[str, Any]] = data.get("counts_by_type", [])
        sv: str = data.get("schema_version", "")

        if total == 0:
            st.success("Detection complete — no candidates found in this run.")
        else:
            st.success(f"Detection complete — {total} candidate(s) found.")

        if counts:
            st.markdown("**Candidates by detector type:**")
            cols = st.columns(max(len(counts), 1))
            for col, entry in zip(cols, counts):
                label = _TYPE_LABELS.get(
                    entry["candidate_type"], entry["candidate_type"]
                )
                col.metric(label, entry["count"])

        if sv:
            st.caption(f"Schema version: `{sv[:16]}…`")

        st.rerun()


def _render_severity_badges(severity_counts: dict[str, int]) -> None:
    """Render a horizontal severity badge row for a candidate group."""
    parts: list[str] = []
    for sev in ("critical", "high", "medium", "low"):
        n = severity_counts.get(sev, 0)
        if n > 0:
            badge = _SEVERITY_BADGE.get(sev, sev.upper())
            parts.append(f"{badge} ×{n}")
    if parts:
        st.caption("  |  ".join(parts))


def _format_refs(refs: list[str]) -> str:
    """Join involved_element_refs with truncation for compact display."""
    if not refs:
        return ""
    truncated = [r[:24] for r in refs[:3]]
    joined = ", ".join(truncated)
    if len(refs) > 3:
        joined += f" +{len(refs) - 3} more"
    return joined


def _format_context(ctx: dict[str, Any]) -> str:
    """Render key context fields as a compact diagnostic string.

    Skips dedupe_key fields (already shown in Elements column) and limits
    output to the four most informative entries.
    """
    skip = {"dedupe_key", "rel_dedupe_key"}
    parts = [f"{k}: {v}" for k, v in ctx.items() if k not in skip]
    return "  |  ".join(str(p) for p in parts[:4])


def _render_candidate_group(group: dict[str, Any]) -> None:
    """Render one candidate type group inside a collapsible expander.

    Groups containing critical-severity candidates start expanded; all
    others start collapsed to reduce visual noise on initial load.
    """
    ctype: str = group.get("candidate_type", "")
    total: int = group.get("total", 0)
    severity_counts: dict[str, int] = group.get("severity_counts", {})
    candidates: list[dict[str, Any]] = group.get("candidates", [])

    label = _TYPE_LABELS.get(ctype, ctype.replace("_", " ").title())
    has_critical = severity_counts.get("critical", 0) > 0

    with st.expander(f"{label} — {total} found", expanded=has_critical):
        _render_severity_badges(severity_counts)

        if not candidates:
            st.caption("No candidates in this group.")
            return

        rows = [
            {
                "ID": c.get("candidate_id", "")[:12] + "…",
                "Severity": c.get("severity", "").upper(),
                "Method": c.get("detection_method", ""),
                "Elements": _format_refs(c.get("involved_element_refs", [])),
                "Context": _format_context(c.get("collision_context", {})),
            }
            for c in candidates
        ]
        st.dataframe(rows, use_container_width=True, hide_index=True)


def _render_candidates_section(run_id: str) -> None:
    """Fetch candidates from cache and render grouped by detector type.

    Reads from GET /api/curation/candidates/{run_id} (backed by the
    5-minute Redis candidate cache).  Shows an informational prompt if
    the cache is empty (generation not yet triggered or TTL expired).
    """
    st.subheader("Candidate Review")

    data = _fetch(f"/api/curation/candidates/{run_id}")

    if data is None:
        st.warning(
            "Cannot reach the candidates endpoint — list unavailable. "
            "Check that the API server is running."
        )
        return

    if data.get("status") == "error":
        for e in data.get("errors", []):
            st.error(f"[{e.get('code')}] {e.get('message')}")
        return

    groups: list[dict[str, Any]] = data.get("groups", [])
    total: int = data.get("total_count", 0)
    sv: str = data.get("schema_version", "")

    if not groups:
        st.info(
            "No candidates loaded yet.  Click **Generate Candidates** above "
            "to run detection, or wait if a previous run is in progress."
        )
        return

    col_total, col_types = st.columns([1, 3])
    col_total.metric("Total Candidates", total)
    col_types.metric("Detector Types with Findings", len(groups))
    if sv:
        st.caption(f"Schema version: `{sv[:16]}…`")

    st.divider()

    for group in groups:
        _render_candidate_group(group)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    """Curation page entry point, called by Streamlit on every script rerun."""
    st.set_page_config(
        page_title="neo4all — Curation",
        layout="wide",
        initial_sidebar_state="expanded",
    )

    # All session state access through StateManager (CLAUDE.md §8).
    state = StateManager.get()

    # --- Phase guard: curation requires Phase 4 ---
    if state.phase.value < Phase.CURATION.value:
        st.title("Phase 4: Curation")
        st.warning(
            "Phase 3 (AI-Assisted Extraction) must be completed before running "
            "curation.  Complete extraction and click 'Proceed to Curation' on "
            "the Extraction page."
        )
        return

    run_id = state.run_id
    if not run_id:
        st.error("No active session.  Initialize a session in Phase 0.")
        return

    # --- Sidebar ---
    with st.sidebar:
        st.header("Curation")
        st.caption("Run ID")
        st.code(run_id[:16] + "…", language=None)
        if state.schema_version:
            st.caption("Schema version")
            st.write(state.schema_version[:16] + "…")
        st.divider()
        st.caption(f"API: `{_API_BASE_URL}`")

    # --- Page header ---
    st.title("Phase 4: Curation — Candidate Review")
    st.caption(
        "Deterministic pre-curation: five zero-LLM detectors surface "
        "duplicates, canonical violations, and structural anomalies for human "
        "review before the AI-assisted proposal pipeline (Phase 4 Layer 2)."
    )

    # --- Trigger section ---
    _render_trigger_section(run_id)

    st.divider()

    # --- Candidate list: reads from 5-minute cache ---
    _render_candidates_section(run_id)


if __name__ == "__main__":
    main()
